base_url = "https://example.com"
theme = "papermod"

taxonomies = [
  {name = "tags", feed = true}
]

compile_sass = true

build_search_index = false

[markdown]
highlight_code = true

[extra]
  [extra.papermod]
    title = "CWLog"
    home_title = "개발 & 해킹 좋아하는 사람"
    home_content = "배운 것을 나누고, 기록하며 복기하는 블로그"
    social_icons = [
      { title = "GitHub", url = "https://github.com/wHoIsDReAmer", icon = "github" },
      { title = "Twitter", url = "https://x.com/@neverprogrammer", icon = "twitter" }
    ]
    date_format = "%Y-%m-%d"
    default_toc_open = true
    language_direction = "auto"
    keywords = ["programming", "hacking", "security", "coding", "developer", "develop"]
    default_theme = "dark"
    theme = "dark"
    show_share_icons = true
    show_post_meta = true
    show_breadcrumbs = true
    show_code_copy_buttons = true
    show_post_nav_links = true
    show_taxonomies = true